language: swift
osx_image: xcode10.2
script: make ci
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - make lint
before_deploy:
  - carthage build --no-skip-current
  - carthage archive SodaStand
notifications:
  irc: "chat.freenode.net#repla-development"
deploy:
  provider: releases
  api_key:
    secure: OQoTTIj5Qia68/mddxbiFR2UqPXih1EltvdOrFe+JDy7B28iAqbk9EmAhM0JYZjqrHnpn0aHxdEEri4SxxPmI+HJ0uj0MHJIHkN8tpydcfiDpeBloqEfV5kxTMTUSllCU4mTkJRIawO/0UOKmmg9gqLQuM1utct2p/KNo5yZR0bwO6ms52BkFPUaalTVkKiUIjBw/0cDFzhG2uogpVq2gVodMd0KAwLdKFAKO7sb9HhOuN1hcZLh1o2XCY0Pfw65evl7FVS3ncTSbXBnCv1gctLqn+y4qfBp/1aj2ryDDN4hO+Ad6NeZDBRY5wzTPPLlovJxMUcA3tIgXCvFphXNYagrlkZUiX+sIJlCPZLS336vYlib2KjjgqhQly000gJCFbKYD0AAeaK7MZlh8c9YFW6edUPRmlJoRkazh9Po52js0qt9UYR1h7wS8wEhQUWtb1CM5Q2NG3aom1B3CLyyqv+duVjx7WDsuIvvJ98PcmfMGUdqDppICwtsDQp13oGslxpQ1LJgT950a+oTt6nxtbXSa35FrV3iCZ+ZryycV0IdcuAGOvnSmTM4dUx8Bq+/df11TgFDKetpENYsHbNEVizVaf1m8irzorPvLpb1AOuARyokv7hZ/xkosCIKfJBJ5V5ZL4Fp20BZbhQ3MqpvG1eZKJCDl8gStHXwvgrzA3U=
  file: SodaStand.framework.zip
  skip_cleanup: true
  on:
    repo: repla-app/SodaStand
    tags: true
